server:
  port: 8081

spring:
  data:
    mongodb:
      uri : mongodb://posi:deleatc205@3.36.113.161/geekhub?authSource=admin
#      host: 3.36.113.161
#      port: 27017
#      database: geekhub
#      username : posi
#      password : deleatc205
#      authentication-database : geekhub
