
server:
  port: 9013

spring:
  application:
    name : task-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://k7c205.p.ssafy.io:3306/geekhub
    username: posi
    password: deleatc205

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
logging:
  level:
    root: info
