server:
  port: 8000
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761:eureka

spring:
  application:
    name: apigateway-server
  cloud:
    gateway:
      routes:
        - id: Kafka
          uri: http://localhost:8081
          predicates:
            - Path=/location/**
        - id: UserService
          uri: http://localhost:9003
          predicates:
            - Path=/admin/**

